# Numpy And inbuilt functions

In [3]:
import numpy as np
                        
print(np.__version__)

1.20.3


In [4]:
# conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
l1=[1,2,3,4,5]

In [7]:
arr=np.array(l1)

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(5,)

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
l2=[6,7,8,9,10]
l3=[11,12,13,14,15]
l4=[16,17,18,19,20]

In [12]:
a1=np.array([l2,l3,l4])

In [13]:
a1

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
a1.shape

(3, 5)

In [15]:
a1.reshape(5,3)

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [16]:
a1.reshape(5,3)

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [17]:
a_1=np.array([1,2,3,4])

In [18]:
a_1[3]

4

In [19]:
 a1

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
a1[0:2,0:2]

array([[ 6,  7],
       [11, 12]])

In [21]:
a1[1:3,2:4]

array([[13, 14],
       [18, 19]])

In [22]:
arr=np.arange(0,10,step=2)

In [23]:
arr

array([0, 2, 4, 6, 8])

In [24]:
np.linspace(1,2,50)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [25]:
arr

array([0, 2, 4, 6, 8])

In [26]:
arr[3:]=100

In [27]:
arr

array([  0,   2,   4, 100, 100])

In [28]:
arr[3:]=500

In [29]:
arr

array([  0,   2,   4, 500, 500])

In [34]:
val=2
arr/2

array([  0.,   1.,   2., 250., 250.])

In [36]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [41]:
np.ones((5,6),dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [55]:
np.random.rand(3,3)

array([[0.42881502, 0.53679636, 0.07378769],
       [0.94742324, 0.34309084, 0.61459091],
       [0.24188569, 0.48384538, 0.79839993]])

In [56]:
import seaborn as sb

Matplotlib is building the font cache; this may take a moment.


In [57]:
import pandas as pd