In [5]:
import numpy as np

In [19]:
a1=np.array([[1,2,3,4,5]],np.int8)
a1

array([[1, 2, 3, 4, 5]], dtype=int8)

In [20]:
a1.shape

(1, 5)

In [22]:
a1.dtype

dtype('int8')

In [26]:
print(a1.ndim)

2


In [28]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a2.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
a3=np.zeros((2,2))

In [32]:
a3

array([[0., 0.],
       [0., 0.]])

In [35]:
a3.dtype

dtype('float64')

In [36]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
a4=np.linspace(1,4,4)
a4

array([1., 2., 3., 4.])

In [40]:
a5=np.array([])    

In [41]:
a5

array([], dtype=float64)

In [42]:
a6=np.arange(99)

In [43]:
a6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
a6.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [46]:
a7=[[1,2,3],[4,5,6],[7,8,9]]

In [47]:
arr=np.array(a7)

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr.sum(axis=0)

array([12, 15, 18])

In [51]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [52]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
arr.flat

In [55]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [56]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr.size

9

In [58]:
arr.nbytes

36

In [59]:
arr.argmax()

8

In [60]:
arr.argmin()

0

In [61]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [62]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [63]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [64]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [69]:
arr+arr1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [70]:
arr*arr1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [71]:
np.count_nonzero(arr)

9

In [72]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))